platform :ios, '15.0'
inhibit_all_warnings!
use_frameworks!

target 'coding_task_ios' do
  pod 'FirebaseRemoteConfig', '10.11.0'
  pod 'Kingfisher', '7.8.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end
