# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coding_task_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coding_task_ios

end
